 menu98edb85b00d9527ad5acebe451b3fae6 = {     {"7-Zip FM", "7zFM"},
     {"Archive Manager", "file-roller "},
     {"Brasero", "brasero "},
     {"Calculator", "gcalctool"},
     {"Character Map", "gucharmap"},
     {"Desktop Search", "tracker-needle"},
     {"Disk Utility", "palimpsest"},
     {"Passwords and Keys", "seahorse"},
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Search for Files...", "gnome-search-tool"},
     {"Terminal", "gnome-terminal"},
     {"Tomboy Notes", "tomboy --search"},
     {"Vi IMproved", "gvim -f "},
     {"gedit", "gedit "},
 }

 menude7a22a0c94aa64ba2449e520aa20c99 = {     {"GoldenDict", "goldendict"},
 }

 menu251bd8143891238ecedc306508e29017 = {     {"AisleRiot Solitaire", "sol"},
     {"Chess", "glchess"},
     {"Five or More", "glines"},
     {"Four-in-a-Row", "gnect"},
     {"FreeCell Solitaire", "sol --freecell"},
     {"Iagno", "iagno"},
     {"Klotski", "gnotski"},
     {"Mahjongg", "mahjongg"},
     {"Mines", "gnomine"},
     {"Nibbles", "gnibbles"},
     {"Quadrapassel", "quadrapassel"},
     {"Robots", "gnobots2"},
     {"Sudoku", "gnome-sudoku"},
     {"Tali", "gtali"},
     {"Tetravex", "gnotravex"},
     {"Urban Terror", "urbanterror"},
 }

 menud334dfcea59127bedfcdbe0a3ee7f494 = {     {"Blender", "blender"},
     {"GNU Image Manipulation Program", "gimp-2.6 "},
     {"Image Viewer", "eog "},
     {"Inkscape", "inkscape "},
     {"Shotwell", "shotwell "},
 }

 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH Server Browser", "/usr/bin/bssh"},
     {"Avahi VNC Server Browser", "/usr/bin/bvnc"},
     {"Chromium", "chromium "},
     {"Deluge", "deluge-gtk "},
     {"ELinks", "xterm -e /usr/bin/elinks "},
     {"Ekiga Softphone", "ekiga"},
     {"Empathy", "empathy"},
     {"Epiphany", "epiphany "},
     {"Epiphany Web Bookmarks", "epiphany --bookmarks-editor"},
     {"FileZilla", "filezilla"},
     {"Firefox", "firefox "},
     {"Google Chrome", "/opt/google/chrome/google-chrome "},
     {"Remote Desktop Viewer", "vinagre "},
     {"Zenmap", "zenmap "},
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh "},
 }

 menudf814135652a5a308fea15bff37ea284 = {     {"Dictionary", "gnome-dictionary"},
     {"Evolution", "evolution "},
     {"GoldenDict", "goldendict"},
     {"LibreOffice ", "libreoffice "},
     {"LibreOffice Calc", "libreoffice --calc "},
     {"LibreOffice Draw", "libreoffice --draw "},
     {"LibreOffice Impress", "libreoffice --impress "},
     {"LibreOffice Math", "libreoffice --math "},
     {"LibreOffice Writer", "libreoffice --writer "},
     {"Zathura", "zathura "},
 }

 menu6311ae17c1ee52b36e68aaf4ad066387 = {     {"Adobe Flash Player", "flash-player-properties"},
     {"IBus Preferences", "ibus-setup"},
     {"Messaging and VoIP Accounts", "empathy-accounts"},
     {"NVIDIA X Server Settings", "/usr/bin/nvidia-settings"},
     {"Search and Indexing", "tracker-preferences"},
 }

 menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {     {"Qt Assistant", "/usr/bin/assistant"},
     {"Qt Designer", "/usr/bin/designer"},
     {"Qt Linguist", "/usr/bin/linguist"},
 }

 menu52dd1c847264a75f400961bfb4d1c849 = {     {"Audacity", "audacity"},
     {"Audio CD Extractor", "sound-juicer "},
     {"Banshee Media Player", "banshee --redirect-log --play-enqueued "},
     {"Brasero", "brasero "},
     {"Cheese", "cheese"},
     {"GNOME MPlayer", "gnome-mplayer "},
     {"Movie Player", "totem "},
     {"OSD Lyrics", "osdlyrics"},
     {"OpenShot Video Editor", "openshot "},
     {"QT V4L2 test Utility", "qv4l2"},
     {"Sound Recorder", "gnome-sound-recorder"},
 }

 menuee69799670a33f75d45c57d1d1cd0ab3 = {     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Configuration Editor", "gconf-editor"},
     {"Disk Usage Analyzer", "baobab"},
     {"Htop", "xterm -e htop"},
     {"IBus", "ibus-daemon --xim"},
     {"Log File Viewer", "gnome-system-log"},
     {"Network Tools", "gnome-nettool"},
     {"Oracle VM VirtualBox", "VirtualBox "},
     {"System Monitor", "gnome-system-monitor"},
     {"System Monitor Preference", "system-monitor-applet-config"},
     {"Wireshark", "wireshark"},
     {"dconf Editor", "dconf-editor"},
     {"rxvt-unicode", "urxvt"},
 }

 menud146f3eb249e9b43bd562738e9ef02a7 = {     {"Caribou", "caribou"},
     {"Dasher", "dasher"},
     {"On-Screen Keyboard", "gok"},
     {"Orca", "orca --replace"},
 }

xdgmenu = {    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
    {"Universal Access", menud146f3eb249e9b43bd562738e9ef02a7},
}

